# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_code/gui/ui/preferenceview.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreferenceView(object):
    def setupUi(self, PreferenceView):
        PreferenceView.setObjectName("PreferenceView")
        PreferenceView.resize(441, 264)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferenceView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.optionsLayout = QtWidgets.QVBoxLayout()
        self.optionsLayout.setObjectName("optionsLayout")
        self.verticalLayout.addLayout(self.optionsLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferenceView)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PreferenceView)
        self.buttonBox.accepted.connect(PreferenceView.accept)
        self.buttonBox.rejected.connect(PreferenceView.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferenceView)

    def retranslateUi(self, PreferenceView):
        _translate = QtCore.QCoreApplication.translate
        PreferenceView.setWindowTitle(_translate("PreferenceView", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PreferenceView = QtWidgets.QDialog()
    ui = Ui_PreferenceView()
    ui.setupUi(PreferenceView)
    PreferenceView.show()
    sys.exit(app.exec_())
